### ISSUE TITLE
How to use TrajStat by scripts

### ISSUE THREAD

**Issue by xigrug** [Yaqiang/TrajStat#1]
Now I have get the hysplit output trajectory file. I want to know how to do next by a script not in UI, as following:

1. Convert end trajetory files to .tgs files. Then join .tgs files to one file.
2. Convert .tgs file to trajectory line shape file and add the shape file into the project.
3. Show press profile of the trajectories.
4. Add measurement data into the trajectories.
5. Select polluted trajectories.
6. Cluster calculation to the trajectories.
7. Calculate mean trajectory of cluster and add the cluster line shape file into the project.
8. Decide cluster number.
9. Add cluster to each trajectory.
10. Do cluster statistics and find the pathways of SDS.
11. Create grid polygon shape layers of PSCF and CWT.
12. PSCF and CWT analysis.

**Comment by xigrug** [comment]
And how to add the output values of hysplit (like PRESSURE,AIR_TEMP,RAINFALL,MIXDEPTH,RELHUMID,SPCHUMID,H2OMIXRA,TERR_MSL) into the shapefile？

I find some questions https://hysplitbbs.arl.noaa.gov/viewtopic.php?t=1502

**Comment by Yaqiang** [comment]
MeteoInfoLab includes Jython engine, so you can use TrajStat.jar in script. Check here for detailed description: https://www.jython.org/jythonbook/en/1.0/JythonAndJavaIntegration.html .

Trajectories were added in a line layer so the variables of AIR_TEMP, RAINFALL.. of each end point can not be included in the shape file. You can created point shape file from hysplit output file with that variables. Or you can do analysis directly using the hysplit output trajectory files.

**Comment by ewingzhang** [comment]
I have the same issue.How to use Trajstat.jar in java??
